---
AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
Metrics/LineLength:
  IgnoredPatterns:
    - !ruby ^#
    - !ruby ^\s*puts
Metrics/MethodLength:
  Exclude:
    - 'Rakefile'
