FROM solr:8.2
LABEL maintainer="mark.cooper@lyrasis.org"

ENV ARCLIGHT_VERSION=0.3.0

USER root

RUN wget -O arclight-${ARCLIGHT_VERSION}.zip https://github.com/sul-dlss/arclight/archive/v${ARCLIGHT_VERSION}.zip && \
    unzip arclight-${ARCLIGHT_VERSION}.zip && \
    mkdir -p /opt/solr/server/solr/configsets/arclight && \
    cp -r arclight-${ARCLIGHT_VERSION}/solr/conf /opt/solr/server/solr/configsets/arclight

USER solr
