---
version: '3'
services:
  indexer:
    image: arclight/indexer
    build:
      context: .
      dockerfile: Dockerfile.indexer
    depends_on:
      - solr_indexer
    restart: on-failure
    environment:
      SOLR_URL: http://solr_indexer:8983/solr/arclight
    command:
      - bundle
      - exec
      - rake
      - arclight:oai:index
  solr_indexer:
    image: arclight/solr
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8984:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - arclight
      - /opt/solr/server/solr/configsets/arclight
