FROM solr:7.5
LABEL maintainer="mark.cooper@lyrasis.org"

RUN wget -O arclight-master.zip https://github.com/sul-dlss/arclight/archive/master.zip && \
    unzip arclight-master.zip && \
    mkdir -p /opt/solr/server/solr/configsets/arclight && \
    cp -r arclight-master/solr/conf /opt/solr/server/solr/configsets/arclight
