---
version: '3'
services:
  indexer:
    image: arclight/indexer
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.indexer
    environment:
      FAD_URL: https://ka2v1g7ub2.execute-api.us-west-2.amazonaws.com
      FAD_ENV: dev
      FAD_TOKEN: abc123
      REPOSITORY_ID: sample
      REPOSITORY_URL: https://raw.githubusercontent.com/sul-dlss/arclight/master/spec/fixtures/config/repositories.yml
      SOLR_URL: http://127.0.0.1:8983/solr/arclight
    command:
      - bundle
      - exec
      - rake
      - arclight:index:fad
