---
version: '3'
services:
  indexer:
    image: arclight/indexer
    build:
      context: .
      dockerfile: Dockerfile.indexer
    depends_on:
      - solr
    restart: on-failure
    environment:
      - "INDEXER_CONFIG_URL=https://raw.githubusercontent.com/projectblacklight/arclight/v0.4.0/lib/arclight/traject/ead2_config.rb"
      - "OAI_ENDPOINT=https://archivesspace.lyrasistechnology.org/oai"
      - "REPOSITORY_URL=https://s3-us-west-2.amazonaws.com/as-public-shared-files/dts/dts.repo.yml"
      - "SOLR_URL=http://solr:8983/solr/arclight"
    command:
      - bundle
      - exec
      - rake
      - arclight:index:oai[1970-01-01]
  solr:
    image: arclight/solr
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - arclight
      - /opt/solr/server/solr/configsets/arclight
