demo:
  name: 'Demo Repository'
  visit_note: 'Containers are stored offsite and must be pages 2 to 3 days in advance'
  description: 'Lorem ipsum'
  building: 'My Building'
  address1: 'My Street Address'
  address2: 'My Extra Address'
  city: 'My City'
  state: 'My State'
  zip: '12345'
  country: 'My Country'
  phone: '123-456-7890'
  contact_info: 'My Contact Info'
  thumbnail_url: 'http://example.com/thumbnail_ABC.jpg'
  google_request_url: 'https://docs.google.com/abc123'
  google_request_mappings: 'collection_name=abc&eadid=123'
  restricted: true